### ISSUE TITLE
Errors in Frontend and Backend

### ISSUE THREAD

**Issue by kfinke** [kaystrobach/TYPO3.dyncss#10]
in Install-Tool I get this error after deleting the cache:

"Load extension configuration
The system detected a fatal error during script execution and redirected to this module. Your loaded extensions are now checked for possible problems. After incompatible extensions are unloaded, you can restart the initial action to proceed your request.
Detected Fatal Error
Class 'tx_DynCss_Configuration_BeRegistry' not found in /serverdata/project/typo3conf/ext/dyncss_less/ext_localconf.php on line 3

Incompatible extension found!
The following extensions are not compatible. Please uninstall them and try again. "

In Frontend and Backend I get this error:
"Fatal error: Class 'tx_DynCss_Configuration_BeRegistry' not found in /serverdata/project/typo3conf/ext/dyncss_less/ext_localconf.php on line 3 Call Stack: 0.0013 124932 1. {main}() /var/www/typo3_src/typo3/index.php:0 0.0014 125356 2. require('/var/www/typo3_src/typo3/init.php') /var/www/typo3_src/typo3/index.php:21 3.3527 1122412 3. TYPO3\CMS\Core\Core\Bootstrap->loadTypo3LoadedExtAndExtLocalconf() /var/www/typo3_src/typo3/init.php:49 3.3527 1122428 4. TYPO3\CMS\Core\Core\Bootstrap->loadAdditionalConfigurationFromExtensions() /var/www/typo3_src/typo3/sysext/core/Classes/Core/Bootstrap.php:334 3.3527 1122500 5. TYPO3\CMS\Core\Utility\ExtensionManagementUtility::loadExtLocalconf() /var/www/typo3_src/typo3/sysext/core/Classes/Core/Bootstrap.php:647 3.3531 1122736 6. TYPO3\CMS\Core\Utility\ExtensionManagementUtility::loadSingleExtLocalconfFiles() /var/www/typo3_src/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php:1505 3.4078 1298584 7. require('/serverdata/project/typo3conf/ext/dyncss_less/ext_localconf.php') /var/www/typo3_src/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php:1529 "

**Comment by kaystrobach** [comment]
should be fixed now ... see ter release or latest git master

**Comment by kaystrobach** [comment]
should be fixed now ... see ter release or latest git master
