### ISSUE TITLE
Uncaught TYPO3 Exception while unlink

### ISSUE THREAD

**Issue by tdeuling** [kaystrobach/TYPO3.dyncss#14]
Following unlink needs a '@' or a file_exists() before using unlink:
https://github.com/kaystrobach/TYPO3.dyncss/blob/master/Classes/Parser/AbstractParser.php#L215

#1: PHP Warning: unlink(..../typo3temp/DynCss/import.less-8a40314c-05b3c2ef-9d867cf6.less): No such file or directory in ..../typo3conf/ext/dyncss/Classes/Parser/AbstractParser.php line 215 (More information)

**Comment by kaystrobach** [comment]
mhmm, why? some lines above i check the filemtime, which included an is_file check in the last php versions.

How have you created that kind of error?
