### ISSUE TITLE
Data url is extended with relative path

### ISSUE THREAD

**Issue by solvage** [kaystrobach/TYPO3.dyncss#17]
Hi there,
i got dyncss 0.7.4 and dyncss scss 0.7.1. Giving data-url to url() extends them with relative path.

url('data:image/svg+xml;base64,PD94bWwgdmV]...[');
converts to
url('../../../../fileadmin/templates/default/css/data:image/svg+xml;base64,PD94bWwgdmV]...[');

Any solution for it?
Bye
Patrick

**Comment by kaystrobach** [comment]
Will take a look, should be fixable ;)

**Comment by kaystrobach** [comment]
@solvage please review that patch, if working i will add it to the master and it will be in the next release

**Comment by solvage** [comment]
Like a charm! Thank you very much for your lightning fast support.

**Comment by kaystrobach** [comment]
Feel free to donate :smile: http://donate.kay-strobach.de/
