### ISSUE TITLE
Adding Minifier into dyncss after parsing the css

### ISSUE THREAD

**Issue by baschte** [kaystrobach/TYPO3.dyncss#21]
this script should look pretty good.

https://github.com/matthiasmullie/minify

**Comment by kaystrobach** [comment]
Hi @baschte just thought about that for a while.
We have the following in the TYPO3 core, so IMHO this is out of scope, as we have the postprocessing for all css files already 😄 

```
config {
  concatenateJs = 1
  concatenateCss = 1
  compressJs = 1
  compressCss = 1
}
```

Agree - if so i would close that issue?

**Comment by baschte** [comment]
Sí @kaystrobach 😉
