### ISSUE TITLE
Filepaths in compiled CSS

### ISSUE THREAD

**Issue by realJustmike** [kaystrobach/TYPO3.dyncss#23]
dyncss 0.7.4
dyncss_scss 0.7.1

I have the following path in my style.scss (typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/style.scss):

url(../../../Public/Images/m_menu.svg)

The image is located in:
typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Public/Images/m_menu.svg

The resulting path in the compiled css file looks like this: ?!

../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../../typo3conf/ext/theme_gugler_bootstrap_ipp/Resources/Private/Dyncss/Library/../../../Public/Images/m_menu.svg

**Comment by kaystrobach** [comment]
@realJustmike there is also an issue dealing with uris can you please join #13 i will close this one here as duplicate ... thanks a lot!
