### ISSUE TITLE
Relative URL

### ISSUE THREAD

**Issue by ancpru** [kaystrobach/TYPO3.dyncss#34]
Hi,

Somehow I do not get what happens here:

I use dyncss_scss. The original scss file specifies the following relative url:

  background-image: url(../../Public/Images/header_bg.png); 

In the generated css, I get the following path:

url(../../../../typo3conf/ext/webe_template/Resources/Private/scss/../../Public/Images/header_bg.png)

That's strange, because in the header the css is linked this way:

<link rel="stylesheet" type="text/css" href="/~andreas/typo3devel/typo3-7.6/typo3temp/DynCss/styles.scss-47ceb6a0-a253e820-e8b40148.css?1471737881" media="all">

The rewritten url goes up 4 path levels. 

Obviously this is happening here:

// anything inside TYPO3 has to be adjusted
        return '../../../../' . dirname($this->removePrefixFromString(PATH_site, $this->inputFilename)) . '/' . $url;

But why? The generated css is taken from typo3temp/DynCss, thus the "root" is 2 levels up. Why is a relative path specified 4 levels up? "../../typo3conf/..." should be correct... but "../../../../typo3conf..." is not.

**Comment by kaystrobach** [comment]
Hi,

Please try the version from 2 days ago, it contains a fix for #30 which should fit your problem.
If not please specify:

* TYPO3 version
* phpversion
* duncss_scss version

Thanks a lot
Kay

**Comment by ancpru** [comment]
Hi, 

Unfortunately this change does not fix the problem. 

Could it be, that the problem occurs, if the typo3 installation is not in the root of the web site?

In my case it's a local development enviroment, reachable under:

http://127.0.0.1/~andreas/typo3devel/typo3-7.6/

thus, the generated css is loaded from 

http://127.0.0.1/~andreas/typo3devel/typo3-7.6/typo3temp/DynCss/styles-xxxxxxxxxxx.css

Now the postprocessor rewrites the url by prefixing it with 4 ".." 

As urls inside a css are relative to the css, this means, it searchs the typo3conf directory not in "typo3-7.6" as it would be correct, but in ~andreas

If the typo3 installation was in the root, it would have removed all path elements by going up 4 steps which might work (not tested), but does not work if the installation is in a sub directory of the server

The dyncss-extensions are a big help anyway and it's not a urgent problem as I have worked-around it by passing a override with the absolute path, but of course it would be better if it also worked in typo3 insallations inside sub directories.

Andreas

PS: My Typo3 is 7.6.5 and PHP is 5.5.9

**Comment by kaystrobach** [comment]
If you could create a working PR i will happily test and merge it

Von meinem iPhone gesendet

**Comment by ancpru** [comment]
Hi,

Ok. I will use the work around (passing the absolute URL to the scss) for this project now, but try to modify the dyncss when I am ready with it. If I find a good solution, I will send you an update (I just hope, that the modification does not fix the problem in my environment, but break other environments)

Thanks for the dyncss-extensios. They make things much easier.

Andreas

**Comment by kaystrobach** [comment]
closing for now
