### ISSUE TITLE
AbstractParser compile condition

### ISSUE THREAD

**Issue by tdeuling** [kaystrobach/TYPO3.dyncss#4]
In AbstractParser->compileFile müssen die Conditions geprüft werden, da sonst u.U. die Less-Dateien immer kompiliert werden.

**Comment by kaystrobach** [comment]
@tdeuling ist das erledigt?

**Comment by tdeuling** [comment]
Wir hatten da mal was gemacht. Ich meine das ist erledigt.. ;)

**Comment by kaystrobach** [comment]
ich mach das erstmal zu ...
