### ISSUE TITLE
Large SCSS Files leads to Error 500 in FE 

### ISSUE THREAD

**Issue by misterboe** [kaystrobach/TYPO3.dyncss#44]
When i try to compile very large SCSS Files i get a error 500 in the Frontend. The problem is that i cant debug it. @kaystrobach told me the install tool settings to get details of the problem, but i only get this from the apache log

```
FastCGI: comm with server "/Applications/MAMP/fcgi-bin/php7.0.15.fcgi" aborted: idle timeout (30 sec)
```

I also recognized a php task on my lokal machine that cause 100% load when the FE is called the first time. This task is still running when i get the error 500. After some time it stops without any error in the php log. 

As soon as i use a smaller SCSS file everything works fine.

**Comment by kaystrobach** [comment]
2 options:

* split the files
* or allow your php processes to run longer.
