### ISSUE TITLE
Possibility of creating namespaces

### ISSUE THREAD

**Issue by millemedia** [kaystrobach/TYPO3.dyncss#51]
We are currently working on an aggregator web site. The problem is, that we will have som remote css that can override our selector. Best would be if we can set a namespace to avoid conflicts,

Is there a possibility to realize that?

**Comment by kaystrobach** [comment]
Should be possible with sass, just wrap the remote code in a sass file or strip remote css completely, what i would suggest for security reasons anyway

Recommend reading:

* http://blog.innerht.ml/cascading-style-scripting/

Feel free to reopen, if you still think this is scope for this project, until now i do think it is not.

**Comment by kaystrobach** [comment]
Btw. maybe also worth a look:

* https://coderwall.com/p/xdmceg/how-to-create-scoped-and-namespaced-css-using-sass

**Comment by millemedia** [comment]
Well,  we use extenasion t3sbootstrap V4 for this project. If I create a namespace within sass I will get a TYPO3 exeption from dyn_scss stating, that varaibles are not defined. Is there a possibility to implement the namespace with typoscript?
