### ISSUE TITLE
Warnings because of TYPO3_cliMode check

### ISSUE THREAD

**Issue by CDRO** [kaystrobach/TYPO3.dyncss#60]
This line throws some warnings in PHP 7.2, would it be possible to extend the code to something like below?

https://github.com/kaystrobach/TYPO3.dyncss/blob/762659e6275ae6190fe450e433c39aa9da4e1bfd/Classes/Service/DyncssService.php#L47

```php
} elseif (TYPO3_MODE === 'BE' && (!defined('TYPO3_cliMode') || !TYPO3_cliMode)) {
```

**Comment by kaystrobach** [comment]
sure, feel free to open a pull request, i will happily review it.

**Comment by pniederlag** [comment]
This PR https://github.com/kaystrobach/TYPO3.dyncss/pull/55 is addressing the issue and working fine for me

**Comment by kaystrobach** [comment]
should be solved in master
