### ISSUE TITLE
Error with php 7.2

### ISSUE THREAD

**Issue by Finulin** [kaystrobach/TYPO3.dyncss#62]
If i try to install dyncss i became the following error-message in the backend:

PHP Warning: Use of undefined constant TYPO3_cliMode - assumed 'TYPO3_cliMode' (this will throw an Error in a future version of PHP) in /var/www/vhosts/dev05.master-ble-prered.ble.de/htdocs/typo3conf/ext/dyncss/Classes/Service/DyncssService.php line 47

i use php 7.2

**Comment by kaystrobach** [comment]
There are already 2 PRs fixing that, so i clise it for now, please follow up in one of them.

Thank you for reporting

**Comment by kaystrobach** [comment]
please check latest release and reopen, if still valid
