### ISSUE TITLE
scss compressed file as http/2 push preload-link

### ISSUE THREAD

**Issue by hoezaykut** [kaystrobach/TYPO3.dyncss#67]
Hello, 

i am not sure, if this extension is responsible to compressed files in hook-depedence of the t3sbootstrap-extension (i think so)

<link rel="stylesheet" type="text/css" href="/typo3temp/DynCss/bootstrap.scss-123456789.css?1539284572" media="all">

I want to change to this (example): <link **rel="preload"** href="/typo3temp/DynCss/bootstrap.scss-123456789.css?1539284572" **as="style"**>

where is the place to change it realy, i think it is the TslibFeContentPostProcAllHook.php

//Neu, Test, Heiko 14.10.2018 rel=preload as=style
          $linkElements = $xPath->query("//link[@rel='preload' @as='style']");

but my sceduler didnt works for recache ...

**Comment by kaystrobach** [comment]
Thank you for opening a ticket.

* what's your frontend output?
* what's your expected output?
* Is the file linked?

**Comment by kaystrobach** [comment]
no response, feel free to reopen with more information.
