### ISSUE TITLE
dyncss breaks extension configuration in TYPO3 9.5

### ISSUE THREAD

**Issue by kfinke** [kaystrobach/TYPO3.dyncss#73]
Since an update from TYPO3 7.6 to 9.5 the dyncss-extension breaks the extension configuration, so configuration of any extension can be done only by deactivating dyncss.

I get an ajax-error, here is the first part of the error shown:

Error
Call to a member function setAndSaveSessionData() on null

in /html/typo3_update/typo3_src-9.5.15/typo3/sysext/core/Classes/Messaging/FlashMessageQueue.php line 151
     * @param FlashMessage[] $flashMessages
     */
    protected function storeFlashMessagesInSession(array $flashMessages = null)
    {
        $this->getUserByContext()->setAndSaveSessionData($this->identifier, $flashMessages);

**Comment by tdeuling** [comment]
Which version of dyncss do you use?
Did you tried the Github-Master?

**Comment by kfinke** [comment]
Yes, I us the github-master version 0.8.3

**Comment by kaystrobach** [comment]
the extension config is not critical for the usage, but we will take a look into it. may take a couple of days.

**Comment by kfinke** [comment]
Sorry, I had the same version number (0.8.3), but obviously another version of dyncss.
I downloaded the version from github directly now - the error is gone, I can open the extension configuration now.

**Comment by kaystrobach** [comment]
thank you for notifying
