### ISSUE TITLE
Error with Typo3 7.0

### ISSUE THREAD

**Issue by larp-welt** [kaystrobach/TYPO3.dyncss#8]
I know this is a bit out of the use case, because I use DynCSS with Typo3 7.0.

The good news is: **It works!** :-)

The bad news is: I get an error in the backend:

    TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction
    |No class named KayStrobach\Dyncss\Hooks\|

But it still generates CSS out of my less-sources! There is now visible error in the frontend. 

So I still use DynCSS and ignore this error!

**Comment by kaystrobach** [comment]
thank you for reporting!

**Comment by kaystrobach** [comment]
there seems to be a simple renaming  / refactoring problem ...

**Comment by kaystrobach** [comment]
@larp-welt please verify ;D

**Comment by kaystrobach** [comment]
in versions 6.2.10 there may be problems with the autoloader ...

**Comment by larp-welt** [comment]
Works fine now!

Thank you very much!

**Comment by kaystrobach** [comment]
:+1:
