### ISSUE TITLE
Parsing often fails (404 of CSS file)

### ISSUE THREAD

**Issue by arnekolja** [kaystrobach/TYPO3.dyncss#9]
We're having trouble with dyncss (_phpsass … don't know whether it's due to dyncss or dyncss_phpsass, sorry if I'm posting at the wrong place).

We have an SCSS file that imports a few other SCSS files. And every now and then parsing fails and the CSS file is referenced, but not generated.

We have no clue how to troubleshoot this, because there is nothing in the logs so far. Today we got it working by removing an commented out @import. Funny thing: after changing it back, it still worked.

Could it be a cache problem with one particular imported file, when this happens?

Situation before, resulting in not generating a file:

    @import "0_helpers";
    @import "10_general";
    /* @import "20_main_menu"; */
    @import "20_menu";
    @import "30_news";
    @import "98_content";

Working version, only removed the 20_main_menu:

    @import "0_helpers";
    @import "10_general";
    @import "20_menu";
    @import "30_news";
    @import "98_content";

And then, it finally worked with version 1 ("before") again. Only thing changed might be a cached file for _20_main_menu.scss.

Do you have an idea what it could be, and/or how to solve this forever? It's occurring in each project we're working on at least once.

**Comment by kaystrobach** [comment]
@arnekolja which versions of the following products to you use:

* php
* typo3
* dyncss
* dyncss_sass / scss 

what content is stored either in typo3temp/Cache/DynCss or typo3temp/DynCss

**Comment by arnekolja** [comment]
* PHP 5.4.34 and 5.3.28dotdeb0 (two machines, same problem)
* TYPO3 6.2.9
* dyncss 0.3.0
* dyncss_phpsass 0.3.1

Content typo3temp/DynCss (typo3temp/Cache/DynCss not present):

* styles.scss-4f8c0d72-f8b4f933-69e56bf6.scss
* styles.scss-4f8c0d72-f8b4f933-69e56bf6.css

But referenced is a file that is not there:

* /typo3temp/DynCss/styles.scss-4f8c0d72-f8b4f933-e63c48df.css

**Comment by kaystrobach** [comment]
ok, you're using a quite old build of dyncss.

I will have to check wether i can add the new debugging features to  the dyncss_phpsass client and make it work with dyncss 0.7.x

any chance to sponsor that?

**Comment by kaystrobach** [comment]
ps: you can try to include the latest version of phpsass on your own: 

copy the content from ```https://github.com/richthegeek/phpsass``` into ```https://github.com/kaystrobach/TYPO3.dyncss_phpsass/tree/master/Resources/Private/Php/PHPSass``` on your harddrive or try the git version of dyncss_phpsass, which should contain these fixes already:

https://github.com/kaystrobach/TYPO3.dyncss_phpsass

**Comment by arnekolja** [comment]
Thanks, I will try this. :-)

And I'll take a look into sponsoring. How much work will be needed? Maybe I could contribute to the code, too.

**Comment by kaystrobach** [comment]
Should be doable in 3-4 hours

**Comment by kaystrobach** [comment]
any news on that?

**Comment by kaystrobach** [comment]
it also put a some updates to github to allow you to install a newer version of dyncss with dyncss_less

**Comment by kaystrobach** [comment]
closed due to inactivity, please reopen, if the ones released later today / git master have the same problem
